apiVersion: v1
kind: Service
metadata:
  name: databaseadmin
  namespace: mutillidae
  labels:
    k8s-app: mutillidae-database-admin
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: mutillidae-database-admin