apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: mutillidae
  labels:
    k8s-app: mutillidae-database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    k8s-app: mutillidae-database