apiVersion: v1
kind: Service
metadata:
  name: directory
  namespace: mutillidae
  labels:
    k8s-app: mutillidae-ldap
spec:
  type: ClusterIP
  ports:
  - port: 389
    targetPort: 389
  selector:
    k8s-app: mutillidae-ldap