apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldapadmin
  namespace: mutillidae
  labels:
    k8s-app: mutillidae-ldap-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mutillidae-ldap-admin
  template:
    metadata:
      labels:
        k8s-app: mutillidae-ldap-admin
    spec:
      containers:
      - name: mutillidae-ldap-admin
        image: webpwnized/mutillidae:ldap_admin
        ports:
        - name: http
          containerPort: 80