apiVersion: v1
name: mutillidae
version: 1.0.0
appVersion: v1.0.0
description: OWASP Mutillidae - https://github.com/webpwnized/mutillidae
home: https://github.com/ngnetworkpro/mutillidae-helm
icon: https://owasp.org/assets/images/logo.svg
maintainers:
- name: Sybil Melton
  email: sybil.melton@droneup.com
  url: https://github.com/ngnetworkpro/